import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage();
const fails = [];
page.on('requestfailed', (r) => fails.push({ url: r.url(), err: r.failure()?.errorText }));
page.on('response', (r) => { if (r.status() >= 400) fails.push({ url: r.url(), status: r.status() }); });
await page.goto('http://localhost:8765/aeline_framer_website.html', { waitUntil: 'networkidle', timeout: 60000 }).catch(()=>{});
await page.waitForTimeout(3000);
console.log(JSON.stringify(fails, null, 2));
await browser.close();
